import imagesProduct from "./assets/img/smokebeef.jpg";
import imagesProduct2 from "./assets/img/brownies.jpeg";
export const Products = [
  {
    id: 1,
    title: "Roti 1",
    description: "Roti Smoked Beef Cheese",
    category: "Roti",
    price: 25000,
    disc: 15,
    rating: 4.5,
    stock: 5,
    imageUrl: imagesProduct,
  },
  {
    id: 2,
    title: "Roti 2",
    description: "Roti Smoked Beef Cheese",
    category: "Roti",
    price: 15000,
    disc: 14,
    rating: 4.7,
    stock: 10,
    imageUrl: imagesProduct,
  },
  {
    id: 3,
    title: "Roti 3",
    description: "Roti Smoked Beef Cheese",
    category: "Roti",
    price: 9500,
    disc: 10,
    rating: 4.6,
    stock: 0,
    imageUrl: imagesProduct,
  },
  {
    id: 4,
    title: "Roti 4",
    description: "Roti Smoked Beef Cheese",
    category: "Roti",
    price: 12500,
    disc: 0,
    stock: 4,
    rating: 5,
    imageUrl: imagesProduct,
  },
  {
    id: 5,
    title: "Roti 5",
    description: "Roti Smoked Beef Cheese",
    category: "Roti",
    price: 10000,
    disc: 11,
    stock: 25,
    rating: 4,
    imageUrl: imagesProduct,
  },
  {
    id: 6,
    title: "Roti 6",
    description: "Roti Smoked Beef Cheese",
    category: "Roti",
    price: 14500,
    disc: 10,
    stock: 15,
    rating: 5,
    imageUrl: imagesProduct,
  },
  {
    id: 7,
    title: "Roti 7",
    description: "Roti Smoked Beef Cheese",
    category: "Roti",
    price: 13000,
    disc: 10,
    stock: 4,
    rating: 4.5,
    imageUrl: imagesProduct2,
  },
  {
    id: 8,
    title: "Roti 8",
    description: "Roti Smoked Beef Cheese",
    category: "Roti",
    price: 13000,
    disc: 10,
    stock: 0,
    rating: 4.5,
    imageUrl: imagesProduct,
  },
  {
    id: 9,
    title: "Roti 9",
    description: "Roti Smoked Beef Cheese",
    category: "Roti",
    price: 14000,
    disc: 0,
    stock: 9,
    rating: 4.9,
    imageUrl: imagesProduct,
  },
  {
    id: 10,
    title: "Roti 10",
    description: "Roti Smoked Beef Cheese",
    category: "Roti",
    price: 17500,
    disc: 10,
    stock: 10,
    rating: 4.5,
    imageUrl: imagesProduct,
  },
  {
    id: 11,
    title: "Roti 11",
    description: "Roti Smoked Beef Cheese",
    category: "Roti",
    price: 19000,
    disc: 0,
    stock: 6,
    rating: 4,
    imageUrl: imagesProduct2,
  },
  {
    id: 12,
    title: "Roti 12",
    description: "Roti Smoked Beef Cheese",
    category: "Roti",
    price: 8500,
    disc: 0,
    stock: 10,
    rating: 5,
    imageUrl: imagesProduct,
  },
  {
    id: 13,
    title: "Roti 13",
    description: "Roti Smoked Beef Cheese",
    category: "Roti",
    price: 17000,
    disc: 0,
    stock: 1,
    rating: 4.5,
    imageUrl: imagesProduct2,
  },
  {
    id: 14,
    title: "Roti 14",
    description: "Roti Smoked Beef Cheese",
    category: "Roti",
    price: 18500,
    disc: 10,
    stock: 0,
    rating: 4,
    imageUrl: imagesProduct,
  },
  {
    id: 15,
    title: "Roti 15",
    description: "Roti Smoked Beef Cheese",
    category: "Roti",
    price: 17500,
    disc: 10,
    stock: 6,
    rating: 4.5,
    imageUrl: imagesProduct2,
  },
  {
    id: 16,
    title: "Roti 16",
    description: "Roti Smoked Beef Cheese",
    category: "Roti",
    price: 11000,
    disc: 5,
    stock: 10,
    rating: 4.5,
    imageUrl: imagesProduct,
  },
  {
    id: 17,
    title: "Roti 17",
    description: "Roti Smoked Beef Cheese",
    category: "Roti",
    price: 8500,
    disc: 5,
    stock: 0,
    rating: 4.5,
    imageUrl: imagesProduct,
  },
  {
    id: 18,
    title: "Roti 18",
    description: "Roti Smoked Beef Cheese",
    category: "Roti",
    price: 14500,
    disc: 11,
    stock: 29,
    rating: 4,
    imageUrl: imagesProduct,
  },
  {
    id: 19,
    title: "Roti 19",
    description: "Roti Smoked Beef Cheese",
    category: "Roti",
    price: 15000,
    disc: 0,
    stock: 15,
    rating: 5,
    imageUrl: imagesProduct,
  },
  {
    id: 20,
    title: "Roti 20",
    description: "Roti Smoked Beef Cheese",
    category: "Roti",
    price: 14000,
    disc: 11,
    stock: 5,
    rating: 5,
    imageUrl: imagesProduct2,
  },
  {
    id: 21,
    title: "Roti 16",
    description: "Roti Smoked Beef Cheese",
    category: "Roti",
    price: 11000,
    disc: 5,
    stock: 10,
    rating: 4.5,
    imageUrl: imagesProduct,
  },
  {
    id: 22,
    title: "Roti 17",
    description: "Roti Smoked Beef Cheese",
    category: "Roti",
    price: 8500,
    disc: 5,
    stock: 0,
    rating: 4.5,
    imageUrl: imagesProduct,
  },
  {
    id: 23,
    title: "Roti 18",
    description: "Roti Smoked Beef Cheese",
    category: "Roti",
    price: 14500,
    disc: 11,
    stock: 29,
    rating: 4,
    imageUrl: imagesProduct,
  },
  {
    id: 24,
    title: "Roti 19",
    description: "Roti Smoked Beef Cheese",
    category: "Roti",
    price: 15000,
    disc: 0,
    stock: 15,
    rating: 5,
    imageUrl: imagesProduct,
  },
  {
    id: 25,
    title: "Roti 20",
    description: "Roti Smoked Beef Cheese",
    category: "Roti",
    price: 14000,
    disc: 11,
    stock: 5,
    rating: 5,
    imageUrl: imagesProduct,
  },

  {
    id: 26,
    title: "Roti 16",
    description: "Roti Smoked Beef Cheese",
    category: "Roti",
    price: 11000,
    disc: 5,
    stock: 10,
    rating: 4.5,
    imageUrl: imagesProduct,
  },
  {
    id: 27,
    title: "Roti 17",
    description: "Roti Smoked Beef Cheese",
    category: "Roti",
    price: 8500,
    disc: 5,
    stock: 0,
    rating: 4.5,
    imageUrl: imagesProduct,
  },
  {
    id: 28,
    title: "Roti 18",
    description: "Roti Smoked Beef Cheese",
    category: "Roti",
    price: 14500,
    disc: 11,
    stock: 29,
    rating: 4,
    imageUrl: imagesProduct,
  },
  {
    id: 29,
    title: "Roti 19",
    description: "Roti Smoked Beef Cheese",
    category: "Roti",
    price: 15000,
    disc: 0,
    stock: 15,
    rating: 5,
    imageUrl: imagesProduct,
  },
  {
    id: 30,
    title: "Roti 20",
    description: "Roti Smoked Beef Cheese",
    category: "Roti",
    price: 14000,
    disc: 11,
    stock: 5,
    rating: 5,
    imageUrl: imagesProduct,
  },
  {
    id: 31,
    title: "Roti 16",
    description: "Roti Smoked Beef Cheese",
    category: "Roti",
    price: 11000,
    disc: 5,
    stock: 10,
    rating: 4.5,
    imageUrl: imagesProduct,
  },
  {
    id: 32,
    title: "Roti 17",
    description: "Roti Smoked Beef Cheese",
    category: "Roti",
    price: 8500,
    disc: 5,
    stock: 0,
    rating: 4.5,
    imageUrl: imagesProduct,
  },
  {
    id: 33,
    title: "Roti 18",
    description: "Roti Smoked Beef Cheese",
    category: "Roti",
    price: 14500,
    disc: 11,
    stock: 29,
    rating: 4,
    imageUrl: imagesProduct,
  },
  {
    id: 34,
    title: "Roti 19",
    description: "Roti Smoked Beef Cheese",
    category: "Roti",
    price: 15000,
    disc: 0,
    stock: 15,
    rating: 5,
    imageUrl: imagesProduct,
  },
  {
    id: 35,
    title: "Roti 20",
    description: "Roti Smoked Beef Cheese",
    category: "Roti",
    price: 14000,
    disc: 11,
    stock: 5,
    rating: 5,
    imageUrl: imagesProduct2,
  },
];
